version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP portu (MassTransit için)
      - "15672:15672" # Yönetim arayüzü
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - eda-network

  order-service:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    container_name: order-service
    ports:
      - "5001:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    networks:
      - eda-network

  payment-service:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    container_name: payment-service
    ports:
      - "5002:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    networks:
      - eda-network

  shipping-service:
    build:
      context: .
      dockerfile: ShippingService/Dockerfile
    container_name: shipping-service
    ports:
      - "5003:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    networks:
      - eda-network

networks:
  eda-network:
    driver: bridge
